export enum CATEGORY {
    BALADA = "BALADA",
    UNIVERSITARIO = "UNIVERSITARIO",
    BAR = "BAR",
    BAR_BALADA = "BAR_BALADA",
    SHOW = "SHOW",
    FESTIVAL = "FESTIVAL",
    FESTA = "FESTA",
  }