export enum FEATURE {
    ESTACIONAMENTO = "ESTACIONAMENTO",
    FUMODROMO = "FUMODROMO",
    VALET = "VALET",
    AREA_ABERTA = "AREA_ABERTA",
    WELCOME_SHOT = "WELCOME_SHOT",
    MESAS = "MESAS",
    OPEN_BAR = "OPEN_BAR",
    AO_VIVO = "AO_VIVO",
    ESQUENTA = "ESQUENTA",
    AFTER = "AFTER",
  }
  